
# Database configuration
db.url=${PROD_DB_HOST}/${PROD_DB_NAME}
db.username=${PROD_DB_USERNAME}
db.password=${PROD_DB_PASSWORD}
db.driver-class-name=com.mysql.cj.jdbc.Driver

show_sql=false

log.level=INFO
